language: python
sudo: required

services:
  - docker

before_install:
  - docker info
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";

install:
  - make build

script:
  - echo "No test to run"

after_success:
  - make push